baseURL = 'https://beckypadget.github.io/'
languageCode = 'en-us'
title = 'SociaNatura'
theme = 'vortisil'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
  customCss = ["css/custom-css.css"]
  title = "SociaNatura"
  author = "Rebecca Padget"
  description = "Social behaviour research"
  profilePicture = "images/treephoto.jpg"
  favicon = "images/favicon.png"

[markup.goldmark.renderer]
    unsafe = true

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"